# Generated by Django 5.2.7 on 2025-10-24 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DarePrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The dare challenge to perform')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this prompt is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dare Prompt',
                'verbose_name_plural': 'Dare Prompts',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='TruthPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='The truth question to ask')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this prompt is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Truth Prompt',
                'verbose_name_plural': 'Truth Prompts',
                'ordering': ['created_at'],
            },
        ),
    ]
